In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\Abhishek Mishra\\Downloads\\Social_Network_Ads.csv")

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [6]:
lable_encoder = LabelEncoder()
temp = df.copy()
temp.iloc[:, 1] = lable_encoder.fit_transform(df.iloc[:, 1])
temp.head()

C:\Users\Abhishek Mishra\AppData\Local\Temp\ipykernel_8860\3902908162.py:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  temp.iloc[:, 1] = lable_encoder.fit_transform(df.iloc[:, 1])


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [7]:
input_feature = ['Gender','Age','EstimatedSalary']

X = temp[input_feature]
y = temp['Purchased']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [9]:
from sklearn.linear_model import LogisticRegression
data = LogisticRegression(random_state=0)
data.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [10]:
y_pred = data.predict(X_test)

In [11]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [13]:
cm

array([[60,  0],
       [40,  0]], dtype=int64)

In [14]:
data.score(X_test, y_test)

0.6

NAIVE BAYES

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [20]:
from sklearn.naive_bayes import GaussianNB
data = GaussianNB()
data.fit(X_train, y_train)

GaussianNB()

In [21]:
from sklearn.metrics import confusion_matrix
y_pred = data.predict(X_test)
confusion_matrix(y_test, y_pred)


array([[66,  2],
       [ 7, 25]], dtype=int64)

In [24]:
data.score(X_test, y_test)

0.91